export const AUTH_REQUESTING = 'requesting'
export const AUTH_REFRESHING = 'refreshing'
export const AUTH_LOGIN = 'login'
export const AUTH_TOKEN_EXPIRED = 'token_expired'
export const AUTH_LOGOUT = 'logout'
